1-module
js-tasks-ru/jsbasic-20230116-2_nisenblvm1 pull request #2
Opened 2023-01-22 11:38 UTC by AleksanderNisenbaum

all 1-module

2023-01-22 11:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-23 15:58 UTC, SinimaWath requested changes

2023-01-23 15:58 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  else{return false}
Если результат операции, boolan, то if не нужен `return Boolean(name) && ....`

2023-01-23 15:58 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`return str.includes(str1.toUpperCase()) || str.includes(str2.toUpperCase())`

2023-01-23 16:34 UTC, AleksanderNisenbaum commented on 1-module/2-task/index.js
> +  else{return false}
Тонко. Пожалуй так бы я не сообразил.

2023-01-23 16:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-01-23 17:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-01-23 17:16 UTC, AleksanderNisenbaum commented
Избавился от if в указанных задачах

2023-01-24 10:48 UTC, closed without merging